"""Strict finite Rankin bound for the Rosser medium-prime presieve.

The first-failure decomposition proving the bound is in the manuscript.
This script certifies its finite positive sum, not external sieve estimates.
Every prime is generated by a complete integer Eratosthenes sieve.
"""
import json
import math
import time
from pathlib import Path
from fractions import Fraction
from flint import arb, ctx


def odd_primes_to(n):
    flags = bytearray(b'\x01') * (n + 1)
    flags[:2] = b'\x00\x00'
    for p in range(2, math.isqrt(n) + 1):
        if flags[p]:
            flags[p*p:n+1:p] = b'\x00' * ((n-p*p)//p + 1)
    return [p for p in range(3, n + 1, 2) if flags[p]]


def degree_thresholds(T, u):
    """Smallest integer r with r^(3b) T^(kb)>=T^a, for each k."""
    values = []
    for k in range(math.ceil(u)+1):
        exponent = u.numerator-k*u.denominator
        if exponent <= 0:
            values.append(1)
            continue
        target = T**exponent
        power = 3*u.denominator
        if T**power < target:
            values.append(T+1)
            continue
        lo,hi = 1,T
        while lo<hi:
            mid = (lo+hi)//2
            if mid**power >= target:
                hi = mid
            else:
                lo = mid+1
        assert lo**power >= target and (lo-1)**power < target
        values.append(lo)
    return values


def certify_rankin(T=5_000_000, w=5, u=Fraction(53,8), sigma_numerator=2,
                   sigma_denominator=11, progress=True, prune_degree=True,
                   uniform_epsilon=None):
    assert T >= 10_000 and 2 <= w < T and u >= 3
    assert sigma_numerator > 0 and sigma_denominator > 0
    assert ctx.prec >= 192
    start = time.monotonic()
    u_fraction = Fraction(u)
    u_ball = arb(u_fraction.numerator)/u_fraction.denominator
    u_value = (u_fraction.numerator if u_fraction.denominator == 1
               else str(u_fraction))
    # If u>3, distinct primes imply d*r^2<T^u whenever n+2<=u.
    # Hence the prefix length n exceeds floor(u-2), and its larger-prime
    # subset has degree >=floor(u-2). At u=3, a one-prime equality can occur.
    minimum_degree = (math.floor(u_fraction-2) if prune_degree and u_fraction>3 else 0)
    max_degree = math.ceil(u_fraction) if prune_degree else 0
    thresholds = degree_thresholds(T,u_fraction) if prune_degree else []
    current_degree = minimum_degree
    primes = odd_primes_to(T)
    exact = [p for p in primes if p <= w]
    Q = math.prod(exact)
    V_exact = arb(1)
    for p in exact:
        V_exact *= 1-arb(1)/(p-1)
    medium = [p for p in primes if p > w]
    # For r processed from largest to smallest, product contains precisely
    # the primes p>r. All factors are positive Arb balls.
    product = arb(1)
    total = arb(0)
    inv_product = arb(1)
    small = [arb(1)]+[arb(0)]*max(0,max_degree-1)
    even_tail = arb(1) if max_degree == 0 else arb(0)
    odd_tail = arb(0)
    upper_total = arb(0)
    lower_total = arb(0)
    for count, p in enumerate(reversed(medium), 1):
        g = arb(1)/(p-1)
        p_sigma = arb(p).root(sigma_denominator)**sigma_numerator
        base = g/(1-g)*p_sigma**3
        total += base*product
        if prune_degree:
            while p < thresholds[current_degree]:
                current_degree += 1
        selected_even,selected_odd = even_tail,odd_tail
        for j in range(current_degree,max_degree):
            if j % 2:
                selected_odd += small[j]
            else:
                selected_even += small[j]
        upper_total += base*inv_product*selected_even
        lower_total += base*inv_product*selected_odd
        h = g*p_sigma
        old_even,old_odd = even_tail,odd_tail
        if max_degree == 0:
            even_tail = old_even+h*old_odd
            odd_tail = old_odd+h*old_even
        elif max_degree % 2:
            even_tail = old_even+h*old_odd
            odd_tail = old_odd+h*(old_even+small[-1])
        else:
            even_tail = old_even+h*(old_odd+small[-1])
            odd_tail = old_odd+h*old_even
        for j in range(max_degree-1,0,-1):
            small[j] += h*small[j-1]
        inv_product /= 1-g
        product *= (1+h)/(1-g)
        if progress and count % 500_000 == 0:
            print(f'Rankin: {count}/{len(medium)} primes, '
                  f'{time.monotonic()-start:.1f}s', flush=True)
    T_sigma = arb(T).root(sigma_denominator)**sigma_numerator
    # For rational u this uses only a positive real root and integer power.
    normalizer = T_sigma.root(u_fraction.denominator)**u_fraction.numerator
    unrestricted_gap = total/normalizer
    upper_gap,lower_gap = upper_total/normalizer,lower_total/normalizer
    gap = upper_gap+lower_gap
    if medium and prune_degree:
        assert gap < unrestricted_gap
    else:
        assert gap.overlaps(unrestricted_gap)
    sigma = arb(sigma_numerator)/sigma_denominator
    support = arb(Q).log()+u_ball*arb(T).log()
    b = 2/(arb(T).sqrt()*arb(T).log())
    far = arb('.000006836')/arb(10**12).log()
    if far > b:
        b = far
    else:
        assert b >= far, 'Arb comparison of the product envelope is unresolved'
    coarse_epsilon = (b+arb('.000002964')/arb(T).log()
               +1/(arb(T)-1)+arb('.54')/T).exp()-1
    epsilon = coarse_epsilon
    if uniform_epsilon is not None:
        epsilon = arb(uniform_epsilon)
        assert 0 < epsilon < coarse_epsilon
    result = {
        'status': 'strict finite Arb sum; first-failure proof is an analytic dependency',
        'precision_bits': ctx.prec,
        'presieve_type': 'pure Rosser medium weights, exact smallest-prime weights',
        'T': T, 'exact_cutoff': w, 'exact_presieve_Q_max': Q,
        'exact_product_ball': str(V_exact),
        'u': u_value, 'D0': f'{T}^({u_value})',
        'sigma': f'{sigma_numerator}/{sigma_denominator}',
        'sigma_ball': str(sigma),
        'complete_odd_prime_count': len(primes),
        'medium_prime_count': len(medium),
        'relative_Rosser_gap_ball': str(gap),
        'upper_relative_Rosser_gap_ball': str(upper_gap),
        'lower_relative_Rosser_gap_ball': str(lower_gap),
        'unrestricted_relative_Rosser_gap_ball': str(unrestricted_gap),
        'minimum_larger_subset_degree': minimum_degree,
        'maximum_larger_subset_degree_cutoff': max_degree,
        'degree_thresholds': thresholds,
        'uniform_epsilon_ball': str(epsilon),
        'coarse_uniform_epsilon_ball': str(coarse_epsilon),
        'uniform_product_input': ('ordered finite certificate supplied by caller'
                                  if uniform_epsilon is not None else
                                  'original BJS/JS pointwise envelope'),
        'log_support_cost_ball': str(support),
        'formula': 'D0^(-sigma) sum_(w<r<=T) [g(r)/(1-g(r)) r^(3 sigma) V_(>r)^(-1) times the positive even/odd elementary tail; degree k requires r^(3b) T^(kb)>=T^a and k>=floor(u-2) for u>3]',
        'prime_generation': 'complete integer Eratosthenes sieve; g(p)=1/(p-1)',
        'deleting_primes': 'the complete-prime positive bound dominates every subset',
        'elapsed_seconds': round(time.monotonic()-start, 3),
    }
    return result, epsilon, gap, support


if __name__ == '__main__':
    ctx.prec = 192
    from conditional_chen_uniform_product_certificate import certify_uniform_products
    uniform = certify_uniform_products()
    row = next(r for r in uniform['rows'] if r['T'] == 5_000_000)
    result, epsilon, gap, support = certify_rankin(
        uniform_epsilon=arb(row['ordered_uniform_epsilon_ball']))
    assert epsilon < arb(1)/41200
    assert arb(result['upper_relative_Rosser_gap_ball']) < arb(1)/3620
    assert arb(result['lower_relative_Rosser_gap_ball']) < arb(1)/3560
    Path(__file__).with_name('conditional_chen_uniform_product_certificate.json').write_text(
        json.dumps(uniform, ensure_ascii=False, indent=2)+'\n', encoding='utf-8')
    Path(__file__).with_suffix('.json').write_text(
        json.dumps(result, ensure_ascii=False, indent=2)+'\n', encoding='utf-8')
    print(json.dumps(result, ensure_ascii=False, indent=2))
